[workspace]
exclude = ["crates/mg-android"]
members = [
    "crates/mg-tokens",
    "crates/mg-motion",
    "crates/mg-theme",
    "crates/mg-components",
    "crates/mg-demo",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/sysrv64/material-geek"
rust-version = "1.86"

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
mg-tokens = { path = "crates/mg-tokens" }
mg-motion = { path = "crates/mg-motion" }
mg-theme = { path = "crates/mg-theme" }
mg-components = { path = "crates/mg-components" }
