pub fn icon_codepoint(name: &str) -> Option<char> {
    let cp = match name {
        "add" => 0xE145,
        "arrow_back" => 0xE5C4,
        "arrow_forward" => 0xE5C8,
        "brush" => 0xE3AE,
        "call" => 0xF0D4,
        "check" => 0xE668,
        "close" => 0xE5CD,
        "code" => 0xE86F,
        "delete" => 0xE92E,
        "description" => 0xE873,
        "edit" => 0xF097,
        "expand_more" => 0xE5CF,
        "favorite" => 0xE87E,
        "history" => 0xE8B3,
        "home" => 0xE9B2,
        "image" => 0xE3F4,
        "link" => 0xE250,
        "mail" => 0xE159,
        "menu" => 0xE5D2,
        "more_vert" => 0xE5D4,
        "notifications" => 0xE7F5,
        "palette" => 0xE40A,
        "person" => 0xF0D3,
        "search" => 0xEF7A,
        "send" => 0xE163,
        "settings" => 0xE8B8,
        "share" => 0xE80D,
        "terminal" => 0xEB8E,
        "tune" => 0xE429,
        "visibility_off" => 0xE8F5,
        _ => return None,
    };
    Some(char::from_u32(cp).unwrap_or('\u{FFFD}'))
}
